# Generated by Django 2.2.2 on 2020-11-24 18:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noti',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('registered_at', models.DateTimeField(auto_now=True)),
                ('FILE', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
